country_list = [
    {'name': 'Afghanistan', 'chosen': False},
    {'name': 'Albania', 'chosen': False},
    {'name': 'Algeria', 'chosen': False},
    {'name': 'Andorra', 'chosen': False},
    {'name': 'Angola', 'chosen': False},
    {'name': 'Antigua and Barbuda', 'chosen': False},
    {'name': 'Argentina', 'chosen': False},
    {'name': 'Armenia', 'chosen': False},
    {'name': 'Australia', 'chosen': False},
    {'name': 'Austria', 'chosen': False},
    {'name': 'Azerbaijan', 'chosen': False},
    {'name': 'Bahamas', 'chosen': False},
    {'name': 'Bahrain', 'chosen': False},
    {'name': 'Bangladesh', 'chosen': False},
    {'name': 'Barbados', 'chosen': False},
    {'name': 'Belarus', 'chosen': False},
    {'name': 'Belgium', 'chosen': False},
    {'name': 'Belize', 'chosen': False},
    {'name': 'Benin', 'chosen': False},
    {'name': 'Bhutan', 'chosen': False},
    {'name': 'Bolivia', 'chosen': False},
    {'name': 'Bosnia and Herzegovina', 'chosen': False},
    {'name': 'Botswana', 'chosen': False},
    {'name': 'Brazil', 'chosen': False},
    {'name': 'Brunei', 'chosen': False},
    {'name': 'Bulgaria', 'chosen': False},
    {'name': 'Burkina Faso', 'chosen': False},
    {'name': 'Burundi', 'chosen': False},
    {'name': 'Cambodia', 'chosen': False},
    {'name': 'Cameroon', 'chosen': False},
    {'name': 'Canada', 'chosen': False},
    {'name': 'Cape Verde', 'chosen': False},
    {'name': 'Central African Republic', 'chosen': False},
    {'name': 'Chad', 'chosen': False},
    {'name': 'Chile', 'chosen': False},
    {'name': 'China', 'chosen': False},
    {'name': 'Colombia', 'chosen': False},
    {'name': 'Comoros', 'chosen': False},
    {'name': 'Congo (Brazzaville)', 'chosen': False},
    {'name': 'Congo (Kinshasa)', 'chosen': False},
    {'name': 'Costa Rica', 'chosen': False},
    {'name': 'Croatia', 'chosen': False},
    {'name': 'Cuba', 'chosen': False},
    {'name': 'Cyprus', 'chosen': False},
    {'name': 'Czech Republic', 'chosen': False},
    {'name': 'Denmark', 'chosen': False},
    {'name': 'Djibouti', 'chosen': False},
    {'name': 'Dominica', 'chosen': False},
    {'name': 'Dominican Republic', 'chosen': False},
    {'name': 'East Timor', 'chosen': False},
    {'name': 'Ecuador', 'chosen': False},
    {'name': 'Egypt', 'chosen': False},
    {'name': 'El Salvador', 'chosen': False},
    {'name': 'Equatorial Guinea', 'chosen': False},
    {'name': 'Eritrea', 'chosen': False},
    {'name': 'Estonia', 'chosen': False},
    {'name': 'Eswatini', 'chosen': False},
    {'name': 'Ethiopia', 'chosen': False},
    {'name': 'Fiji', 'chosen': False},
    {'name': 'Finland', 'chosen': False},
    {'name': 'France', 'chosen': False},
    {'name': 'Gabon', 'chosen': False},
    {'name': 'Gambia', 'chosen': False},
    {'name': 'Georgia', 'chosen': False},
    {'name': 'Germany', 'chosen': False},
    {'name': 'Ghana', 'chosen': False},
    {'name': 'Greece', 'chosen': False},
    {'name': 'Grenada', 'chosen': False},
    {'name': 'Guatemala', 'chosen': False},
    {'name': 'Guinea', 'chosen': False},
    {'name': 'Guinea-Bissau', 'chosen': False},
    {'name': 'Guyana', 'chosen': False},
    {'name': 'Haiti', 'chosen': False},
    {'name': 'Honduras', 'chosen': False},
    {'name': 'Hungary', 'chosen': False},
    {'name': 'Iceland', 'chosen': False},
    {'name': 'India', 'chosen': False},
    {'name': 'Indonesia', 'chosen': False},
    {'name': 'Iran', 'chosen': False},
    {'name': 'Iraq', 'chosen': False},
    {'name': 'Ireland', 'chosen': False},
    {'name': 'Israel', 'chosen': False},
    {'name': 'Italy', 'chosen': False},
    {'name': 'Jamaica', 'chosen': False},
    {'name': 'Japan', 'chosen': False},
    {'name': 'Jordan', 'chosen': False},
    {'name': 'Kazakhstan', 'chosen': False},
    {'name': 'Kenya', 'chosen': False},
    {'name': 'Kiribati', 'chosen': False},
    {'name': 'Korea, North', 'chosen': False},
    {'name': 'Korea, South', 'chosen': False},
    {'name': 'Kosovo', 'chosen': False},
    {'name': 'Kuwait', 'chosen': False},
    {'name': 'Kyrgyzstan', 'chosen': False},
    {'name': 'Laos', 'chosen': False},
    {'name': 'Latvia', 'chosen': False},
    {'name': 'Lebanon', 'chosen': False},
    {'name': 'Lesotho', 'chosen': False},
    {'name': 'Liberia', 'chosen': False},
    {'name': 'Libya', 'chosen': False},
    {'name': 'Liechtenstein', 'chosen': False},
    {'name': 'Lithuania', 'chosen': False},
    {'name': 'Luxembourg', 'chosen': False},
    {'name': 'Madagascar', 'chosen': False},
    {'name': 'Malawi', 'chosen': False},
    {'name': 'Malaysia', 'chosen': False},
    {'name': 'Maldives', 'chosen': False},
    {'name': 'Mali', 'chosen': False},
    {'name': 'Malta', 'chosen': False},
    {'name': 'Marshall Islands', 'chosen': False},
    {'name': 'Mauritania', 'chosen': False},
    {'name': 'Mauritius', 'chosen': False},
    {'name': 'Mexico', 'chosen': False},
    {'name': 'Micronesia', 'chosen': False},
    {'name': 'Moldova', 'chosen': False},
    {'name': 'Monaco', 'chosen': False},
    {'name': 'Mongolia', 'chosen': False},
    {'name': 'Montenegro', 'chosen': False},
    {'name': 'Morocco', 'chosen': False},
    {'name': 'Mozambique', 'chosen': False},
    {'name': 'Myanmar', 'chosen': False},
    {'name': 'Namibia', 'chosen': False},
    {'name': 'Nauru', 'chosen': False},
    {'name': 'Nepal', 'chosen': False},
    {'name': 'Netherlands', 'chosen': False},
    {'name': 'New Zealand', 'chosen': False},
    {'name': 'Nicaragua', 'chosen': False},
    {'name': 'Niger', 'chosen': False},
    {'name': 'Nigeria', 'chosen': False},
    {'name': 'North Macedonia', 'chosen': False},
    {'name': 'Norway', 'chosen': False},
    {'name': 'Oman', 'chosen': False},
    {'name': 'Pakistan', 'chosen': False},
    {'name': 'Palau', 'chosen': False},
    {'name': 'Panama', 'chosen': False},
    {'name': 'Papua New Guinea', 'chosen': False},
    {'name': 'Paraguay', 'chosen': False},
    {'name': 'Peru', 'chosen': False},
    {'name': 'Philippines', 'chosen': False},
    {'name': 'Poland', 'chosen': False},
    {'name': 'Portugal', 'chosen': False},
    {'name': 'Qatar', 'chosen': False},
    {'name': 'Romania', 'chosen': False},
    {'name': 'Russia', 'chosen': False},
    {'name': 'Rwanda', 'chosen': False},
    {'name': 'Saint Kitts and Nevis', 'chosen': False},
    {'name': 'Saint Lucia', 'chosen': False},
    {'name': 'Saint Vincent and the Grenadines', 'chosen': False},
    {'name': 'Samoa', 'chosen': False},
    {'name': 'San Marino', 'chosen': False},
    {'name': 'Sao Tome and Principe', 'chosen': False},
    {'name': 'Saudi Arabia', 'chosen': False},
    {'name': 'Senegal', 'chosen': False},
    {'name': 'Serbia', 'chosen': False},
    {'name': 'Seychelles', 'chosen': False},
    {'name': 'Sierra Leone', 'chosen': False},
    {'name': 'Singapore', 'chosen': False},
    {'name': 'Slovakia', 'chosen': False},
    {'name': 'Slovenia', 'chosen': False},
    {'name': 'Solomon Islands', 'chosen': False},
    {'name': 'Somalia', 'chosen': False},
    {'name': 'South Africa', 'chosen': False},
    {'name': 'South Sudan', 'chosen': False},
    {'name': 'Spain', 'chosen': False},
    {'name': 'Sri Lanka', 'chosen': False},
    {'name': 'Sudan', 'chosen': False},
    {'name': 'Suriname', 'chosen': False},
    {'name': 'Sweden', 'chosen': False},
    {'name': 'Switzerland', 'chosen': False},
    {'name': 'Syria', 'chosen': False},
    {'name': 'Taiwan', 'chosen': False},
    {'name': 'Tajikistan', 'chosen': False},
    {'name': 'Tanzania', 'chosen': False},
    {'name': 'Thailand', 'chosen': False},
    {'name': 'Togo', 'chosen': False},
    {'name': 'Tonga', 'chosen': False},
    {'name': 'Trinidad and Tobago', 'chosen': False},
    {'name': 'Tunisia', 'chosen': False},
    {'name': 'Turkey', 'chosen': False},
    {'name': 'Turkmenistan', 'chosen': False},
    {'name': 'Tuvalu', 'chosen': False},
    {'name': 'Uganda', 'chosen': False},
    {'name': 'Ukraine', 'chosen': False},
    {'name': 'United Arab Emirates', 'chosen': False},
    {'name': 'United Kingdom', 'chosen': False},
    {'name': 'United States', 'chosen': False},
    {'name': 'Uruguay', 'chosen': False},
    {'name': 'Uzbekistan', 'chosen': False},
    {'name': 'Vanuatu', 'chosen': False},
    {'name': 'Vatican City', 'chosen': False},
    {'name': 'Venezuela', 'chosen': False},
    {'name': 'Vietnam', 'chosen': False},
    {'name': 'Yemen', 'chosen': False},
    {'name': 'Zambia', 'chosen': False},
    {'name': 'Zimbabwe', 'chosen': False}
]