states = [
    {'name': 'Alabama', 'chosen': False},
    {'name': 'Alaska', 'chosen': False},
    {'name': 'Arizona', 'chosen': False},
    {'name': 'Arkansas', 'chosen': False},
    {'name': 'California', 'chosen': False},
    {'name': 'Colorado', 'chosen': False},
    {'name': 'Connecticut', 'chosen': False},
    {'name': 'Delaware', 'chosen': False},
    {'name': 'Florida', 'chosen': False},
    {'name': 'Georgia', 'chosen': False},
    {'name': 'Hawaii', 'chosen': False},
    {'name': 'Idaho', 'chosen': False},
    {'name': 'Illinois', 'chosen': False},
    {'name': 'Indiana', 'chosen': False},
    {'name': 'Iowa', 'chosen': False},
    {'name': 'Kansas', 'chosen': False},
    {'name': 'Kentucky', 'chosen': False},
    {'name': 'Louisiana', 'chosen': False},
    {'name': 'Maine', 'chosen': False},
    {'name': 'Maryland', 'chosen': False},
    {'name': 'Massachusetts', 'chosen': False},
    {'name': 'Michigan', 'chosen': False},
    {'name': 'Minnesota', 'chosen': False},
    {'name': 'Mississippi', 'chosen': False},
    {'name': 'Missouri', 'chosen': False},
    {'name': 'Montana', 'chosen': False},
    {'name': 'Nebraska', 'chosen': False},
    {'name': 'Nevada', 'chosen': False},
    {'name': 'New Hampshire', 'chosen': False},
    {'name': 'New Jersey', 'chosen': False},
    {'name': 'New Mexico', 'chosen': False},
    {'name': 'New York', 'chosen': False},
    {'name': 'North Carolina', 'chosen': False},
    {'name': 'North Dakota', 'chosen': False},
    {'name': 'Ohio', 'chosen': False},
    {'name': 'Oklahoma', 'chosen': False},
    {'name': 'Oregon', 'chosen': False},
    {'name': 'Pennsylvania', 'chosen': False},
    {'name': 'Rhode Island', 'chosen': False},
    {'name': 'South Carolina', 'chosen': False},
    {'name': 'South Dakota', 'chosen': False},
    {'name': 'Tennessee', 'chosen': False},
    {'name': 'Texas', 'chosen': False},
    {'name': 'Utah', 'chosen': False},
    {'name': 'Vermont', 'chosen': False},
    {'name': 'Virginia', 'chosen': False},
    {'name': 'Washington', 'chosen': False},
    {'name': 'West Virginia', 'chosen': False},
    {'name': 'Wisconsin', 'chosen': False},
    {'name': 'Wyoming', 'chosen': False}
]
